spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "create"

firebase:
  admin:
    credentials:
      path: ".secrets/firebase-admin-sdk.json"
