spring:
  application:
    name: "orca-service"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "create"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

server:
  port: 8082
